#!/usr/bin/env bash
# init.sh — Initialize dev environment for {{stackLabel}} project
# Generated by dev-harness v{{harnessVersion}}

set -euo pipefail

echo "=== {{stackLabel}} Project Setup ==="
echo ""

# Install dependencies
echo "[1/4] Installing dependencies..."
{{installCmd}}

# Set up git hooks (if .git exists)
if [ -d ".git" ]; then
  echo "[2/4] Setting up git hooks..."
  mkdir -p .git/hooks

  # pre-commit: run lint + type check
  cat > .git/hooks/pre-commit << 'HOOK'
#!/usr/bin/env bash
set -euo pipefail
echo "Running pre-commit checks..."
{{lintCmd}} 2>/dev/null || echo "Lint: check failed (non-fatal)"
{{typeCheckCmd}} 2>/dev/null || echo "Type check: failed (non-fatal)"
HOOK
  chmod +x .git/hooks/pre-commit
fi

# Start progress.md
if [ ! -f "progress.md" ]; then
  echo "[3/4] Creating progress.md..."
  cat > progress.md << 'MD'
# Progress: {{stackLabel}}

## Status

| Phase | Status | Last Validated |
|-------|--------|---------------|
| DEFINE | pending | — |
| PLAN | pending | — |
| BUILD | pending | — |
| VERIFY | pending | — |
| SIMPLIFY | pending | — |
| REVIEW | pending | — |
| SHIP | pending | — |

## Sessions

| Date | Session | Outcome |
|------|---------|---------|
MD
fi

# Create harness-config.json if not exists
if [ ! -f "harness-config.json" ]; then
  echo "[4/4] Creating harness-config.json..."
  cat > harness-config.json << 'CFG'
{
  "version": "1.0",
  "stack": "{{stack}}",
  "mode": "copilot",
  "currentPhase": null,
  "paused": false,
  "features": {
    "remaining": 0,
    "passing": 0,
    "total": 0
  },
  "gates": {
    "enabled": false,
    "checks": ["all"]
  },
  "git": {
    "autoCommit": false,
    "autoTag": false,
    "resetOnRetry": false,
    "branch": null,
    "clean": true,
    "hasUpstream": false,
    "lastCommitMessage": null
  },
  "phases": {
    "enabled": ["define", "plan", "build", "verify", "review", "ship"]
  },
  "agents": {
    "tone": {
      "planner": "Analytical and precise. Define clear boundaries.",
      "generator": "Focused and practical. Build what's specified, nothing more.",
      "evaluator": "Skeptical and thorough. Accept only compelling evidence.",
      "simplifier": "Relentless about clarity. Delete more than you add."
    }
  },
  "maxRetries": 3,
  "gateHistory": []
}
CFG
fi

echo ""
echo "=== Setup complete ==="
echo ""
