/**
 * task-prompt — Build task prompts for spawned agents.
 *
 * Generates the instruction text that gets written to harness/current-task.md
 * and passed to the spawned agentic tool. Each task prompt includes:
 *   - Phase context (what phase we're in, what it should produce)
 *   - Feature context (which feature, description)
 *   - Task instructions (task description, acceptance criteria)
 *   - Harness conventions reference
 *   - Validation instruction
 *
 * Usage:
 *   import { buildTaskPrompt, writeTaskPrompt } from './task-prompt.mjs';
 *   const prompt = buildTaskPrompt(targetDir, phase, feature, task);
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadConfig } from './state.mjs';
import { loadFeatureList } from './ralph-inner.mjs';
import { phaseLabel } from './command-helpers.mjs';

/**
 * Build a task prompt string for a spawned agent.
 *
 * @param {string} targetDir
 * @param {string} phase — Current phase name
 * @param {object} feature — Feature object from feature_list.json
 * @param {object} task — Task object from feature_list.json
 * @returns {string} — The complete task prompt
 */
export function buildTaskPrompt(targetDir, phase, feature, task) {
  const { config } = loadConfig(targetDir);
  const stack = config?.stack ?? 'unknown';
  const mode = config?.mode ?? 'copilot';

  let prompt = '';

  // ── Header ──────────────────────────────────────────────────
  prompt += `# Task Assignment — ${phaseLabel(phase)} Phase\n\n`;
  prompt += `**Project:** ${targetDir.split('/').pop()}\n`;
  prompt += `**Stack:** ${stack}\n`;
  prompt += `**Mode:** ${mode}\n\n`;

  // ── Phase context ───────────────────────────────────────────
  prompt += `## Phase Context\n\n`;
  prompt += `You are in the **${phaseLabel(phase)}** phase of the development pipeline.\n`;
  prompt += getPhaseDescription(phase);
  prompt += `\n`;

  // ── Feature context ─────────────────────────────────────────
  if (feature) {
    prompt += `## Feature\n\n`;
    prompt += `**Name:** ${feature.name}\n`;
    prompt += `**ID:** ${feature.id}\n`;
    if (feature.description) {
      prompt += `**Description:** ${feature.description}\n`;
    }
    const tasksDone = (feature.tasks || []).filter(t => t.status === 'complete').length;
    const tasksTotal = (feature.tasks || []).length;
    prompt += `**Progress:** ${tasksDone}/${tasksTotal} tasks complete\n\n`;
  }

  // ── Task instructions ───────────────────────────────────────
  if (task) {
    prompt += `## Your Task\n\n`;
    prompt += `**Task ID:** ${task.id}\n`;
    prompt += `**Description:** ${task.description}\n\n`;
    prompt += `### Instructions\n\n`;
    prompt += `1. Read \`AGENTS.md\` in the project root for project conventions\n`;
    prompt += `2. Implement the task described above\n`;
    prompt += `3. Follow the ${phaseLabel(phase)} phase guidelines\n`;
    prompt += `4. Do NOT work on other tasks — focus only on this one\n`;
    prompt += `5. When done, the harness will validate your work automatically\n\n`;
  } else {
    // Deliverable-retry phase (no specific task)
    prompt += `## Your Deliverable\n\n`;
    prompt += `Produce the deliverable for the ${phaseLabel(phase)} phase.\n`;
    prompt += `Read \`AGENTS.md\` for project conventions and phase requirements.\n`;
    prompt += `When done, the harness will validate your work automatically.\n\n`;
  }

  // ── Validation reminder ─────────────────────────────────────
  prompt += `## Validation\n\n`;
  prompt += `The harness will run gate checks after you complete this task.\n`;
  prompt += `If validation fails, you will be retried with fresh context (up to ${config?.maxRetries ?? 10} times).\n`;
  prompt += `If validation passes, the harness will advance to the next task automatically.\n\n`;

  // ── Conventions reference ───────────────────────────────────
  prompt += `## Project Conventions\n\n`;
  prompt += `- Read \`AGENTS.md\` for coding standards and project structure\n`;
  prompt += `- Read \`harness/config.json\` for current pipeline state\n`;
  if (feature) {
    prompt += `- Read \`harness/features/feature-list.json\` for the full feature/task breakdown\n`;
  }
  prompt += `\n---\n*Generated by dev-harness task-prompt builder*\n`;

  return prompt;
}

/**
 * Get a human-readable description for a phase.
 * @param {string} phase
 * @returns {string}
 */
function getPhaseDescription(phase) {
  const descriptions = {
    init: 'Initialize the project structure and configuration.',
    define: 'Write specifications and define acceptance criteria for all features.',
    plan: 'Decompose features into actionable tasks with dependencies and estimates.',
    build: 'Implement features one task at a time. Each task must pass validation before advancing.',
    verify: 'Validate and test all implemented features. Ensure test coverage meets threshold.',
    simplify: 'Refactor code for clarity. Remove dead code, reduce complexity, improve naming.',
    review: 'Multi-agent committee review. Verify all gates pass, architecture is sound.',
    ship: 'Tag release, update changelog, verify git clean state. Prepare for publication.',
  };
  return descriptions[phase] || `Complete the ${phase} phase deliverable.`;
}

/**
 * Write a task prompt to harness/current-task.md.
 *
 * @param {string} targetDir
 * @param {string} phase
 * @param {object} feature
 * @param {object} task
 * @returns {string} — Path to the written file
 */
export function writeTaskPrompt(targetDir, phase, feature, task) {
  const prompt = buildTaskPrompt(targetDir, phase, feature, task);
  const taskFile = resolve(targetDir, 'harness', 'current-task.md');
  writeFileSync(taskFile, prompt, 'utf-8');
  return taskFile;
}

/**
 * Build a task prompt for the current task in the pipeline.
 * Reads config + feature list to determine what to work on.
 *
 * @param {string} targetDir
 * @returns {{ prompt: string, feature: object|null, task: object|null, phase: string|null }}
 */
export function buildCurrentTaskPrompt(targetDir) {
  const { config, ok } = loadConfig(targetDir);
  if (!ok) {
    return { prompt: '', feature: null, task: null, phase: null };
  }

  const phase = config.currentPhase;
  if (!phase) {
    return { prompt: '', feature: null, task: null, phase: null };
  }

  // For feature-iterate phases, get current feature + task
  const FEATURE_ITERATE = new Set(['build', 'verify', 'simplify']);
  if (FEATURE_ITERATE.has(phase)) {
    const fl = loadFeatureList(targetDir);
    const features = fl.features || [];
    const feature = features.find(f => !f.passes);
    if (!feature) {
      return { prompt: '', feature: null, task: null, phase };
    }
    const task = (feature.tasks || []).find(t => t.status !== 'complete');
    if (!task) {
      return { prompt: '', feature: null, task: null, phase };
    }
    const prompt = buildTaskPrompt(targetDir, phase, feature, task);
    return { prompt, feature, task, phase };
  }

  // Deliverable-retry phase — no specific feature/task
  const prompt = buildTaskPrompt(targetDir, phase, null, null);
  return { prompt, feature: null, task: null, phase };
}
